name: DockerHub
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        BINDER_CACHE: true
        NO_GIT_PUSH: true
        PUBLIC_REGISTRY_CHECK: true

    - name: Trigger OVH mybinder rebuild
      continue-on-error: true
      run: curl -L --connect-timeout 20 --max-time 900 https://ovh.mybinder.org/build/gh/$GITHUB_REPOSITORY/HEAD

    - name: Trigger CurveNote mybinder rebuild
      continue-on-error: true
      run: curl -L --connect-timeout 20 --max-time 900 https://binder.curvenote.dev/build/gh/$GITHUB_REPOSITORY/HEAD

    - name: Trigger GESIS mybinder rebuild
      continue-on-error: true
      run: curl -L --connect-timeout 20 --max-time 900 https://notebooks.gesis.org/binder/build/gh/J08nY/pyecsca-tutorial-ches2024/HEAD
